# Generated by Django 4.1.6 on 2023-02-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaSimulation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seed_particle', models.JSONField(default=list)),
                ('total_particles', models.IntegerField(default=15)),
                ('c1', models.FloatField(default=1.49445)),
                ('c2', models.FloatField(default=1.49445)),
                ('w', models.FloatField(default=0.7298)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('particles', models.JSONField(default=list)),
                ('best_particles', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('swarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.swarm')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_solution', models.JSONField(default=dict)),
                ('best_solution', models.JSONField(default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='GaSimulationResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solution', models.JSONField(default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.gasimulation')),
            ],
        ),
    ]
