# Generated by Django 4.1.6 on 2023-02-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GaSimulation',
            new_name='Ga',
        ),
        migrations.RenameModel(
            old_name='GaSimulationResults',
            new_name='GaResults',
        ),
    ]
