# Generated by Django 4.1.6 on 2023-02-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_gasimulation_ga_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seed',
        ),
    ]
