# Generated by Django 4.1.6 on 2023-02-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_delete_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeedResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iteration', models.IntegerField(default=0)),
                ('mse', models.FloatField(default=0)),
                ('solution', models.JSONField(default=dict)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.seed')),
            ],
        ),
    ]
